Add check for matching tag

diff --git a/.github/workflows/build-docker.yml b/.github/workflows/build-docker.yml
--- a/.github/workflows/build-docker.yml
+++ b/.github/workflows/build-docker.yml
@@ -18,6 +18,7 @@ on:
       - Dockerfile
       - renv.lock
       - requirements.txt
+      - current-modules.json
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -28,6 +29,20 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      - name: Check out the repo
+        uses: actions/checkout@v5
+
+      - name: Check that current-modules release-tag matches git tag
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          GIT_TAG=${GITHUB_REF#refs/tags/}
+          MODULES_TAG=$(jq -r '.release-tag' current-modules.json)
+          if [ "$GIT_TAG" != "$MODULES_TAG" ]; then
+            echo "Error: current-modules.json release-tag ($MODULES_TAG) does not match git tag ($GIT_TAG)"
+            echo "Please update release-tag in current-modules.json to match the git tag (and modules, if needed), then update the GitHub release accordingly."
+            exit 1
+          fi
+
       - name: Load 1Password secrets
         uses: 1password/load-secrets-action@v2
         with:
